fix cronjob
Fixing the error:
src/main.zig:43:71: error: type 'json.static.Parsed([]main.Joke)' does not support indexing
src/main.zig:43:71: note: operand must be an array, slice, tuple, or vector

Local development in outdated zig version.
Updated to zig-0.11.0-dev.4406+d370005d3.